{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [],
   "source": [
    "import threading\n",
    "import sys; sys.setswitchinterval(10 ** -10)\n",
    "\n",
    "class Counter:\n",
    "    def __init__(self, target):\n",
    "        self.value = 0\n",
    "        self.target = target\n",
    "        \n",
    "    def update(self):\n",
    "        current_value = self.value\n",
    "        breakpoint()\n",
    "        self.value = current_value + 1\n",
    "        \n",
    "    def run(self):\n",
    "        threads = [threading.Thread(target=self.update)\n",
    "                   for _ in range(self.target)]\n",
    "        for t in threads:\n",
    "            t.start()\n",
    "        for t in threads:\n",
    "            t.join()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [],
   "source": [
    "import unittest\n",
    "\n",
    "class TestCounter(unittest.TestCase):\n",
    "    def setUp(self):\n",
    "        self.small_params = 5\n",
    "        self.med_params = 5000\n",
    "        self.large_params = 10000\n",
    "    \n",
    "    def test_small(self):\n",
    "        small_counter = Counter(self.small_params)\n",
    "        small_counter.run()\n",
    "        self.assertEqual(small_counter.value, self.small_params)\n",
    "        \n",
    "    def test_med(self):\n",
    "        med_counter = Counter(self.med_params)\n",
    "        med_counter.run()\n",
    "        self.assertEqual(med_counter.value, self.med_params)\n",
    "        \n",
    "    def test_large(self):\n",
    "        large_counter = Counter(self.large_params)\n",
    "        large_counter.run()\n",
    "        self.assertEqual(large_counter.value, self.large_params)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "test_large (__main__.TestCounter) ... FAIL\n",
      "test_med (__main__.TestCounter) ... FAIL\n",
      "test_small (__main__.TestCounter) ... ok\n",
      "\n",
      "======================================================================\n",
      "FAIL: test_large (__main__.TestCounter)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-57-4ed47b9310ba>\", line 22, in test_large\n",
      "    self.assertEqual(large_counter.value, self.large_params)\n",
      "AssertionError: 9996 != 10000\n",
      "\n",
      "======================================================================\n",
      "FAIL: test_med (__main__.TestCounter)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-57-4ed47b9310ba>\", line 17, in test_med\n",
      "    self.assertEqual(med_counter.value, self.med_params)\n",
      "AssertionError: 4999 != 5000\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 3 tests in 0.890s\n",
      "\n",
      "FAILED (failures=2)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x10dc2e8d0>"
      ]
     },
     "execution_count": 58,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=2, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "> <ipython-input-61-066f5069e308>(12)update()\n",
      "-> self.value = current_value + 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-328879:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-61-066f5069e308>\", line 11, in update\n",
      "    breakpoint()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 1610, in set_trace\n",
      "    pdb.set_trace(sys._getframe().f_back)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 326, in set_trace\n",
      "    self.reset()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 196, in reset\n",
      "    bdb.Bdb.reset(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 57, in reset\n",
      "    linecache.checkcache()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/compilerop.py\", line 157, in check_linecache_ipython\n",
      "    linecache._checkcache_ori(*args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 66, in checkcache\n",
      "    entry = cache[filename]\n",
      "KeyError: '<ipython-input-20-91782a3e1017>'\n",
      "Exception in thread Thread-328876:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-61-066f5069e308>\", line 11, in update\n",
      "    breakpoint()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 1610, in set_trace\n",
      "    pdb.set_trace(sys._getframe().f_back)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 326, in set_trace\n",
      "    self.reset()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 196, in reset\n",
      "    bdb.Bdb.reset(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 57, in reset\n",
      "    linecache.checkcache()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/compilerop.py\", line 157, in check_linecache_ipython\n",
      "    linecache._checkcache_ori(*args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 66, in checkcache\n",
      "    entry = cache[filename]\n",
      "KeyError: '<ipython-input-29-4047ee89f2b5>'\n",
      "Exception in thread Thread-328880:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 74, in checkcache\n",
      "    stat = os.stat(fullname)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '<ipython-input-1-58721f65359e>'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-61-066f5069e308>\", line 11, in update\n",
      "    breakpoint()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 1610, in set_trace\n",
      "    pdb.set_trace(sys._getframe().f_back)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 326, in set_trace\n",
      "    self.reset()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 196, in reset\n",
      "    bdb.Bdb.reset(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 57, in reset\n",
      "    linecache.checkcache()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/compilerop.py\", line 157, in check_linecache_ipython\n",
      "    linecache._checkcache_ori(*args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 76, in checkcache\n",
      "    del cache[filename]\n",
      "KeyError: '<ipython-input-1-58721f65359e>'\n",
      "Exception in thread Thread-328875:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-61-066f5069e308>\", line 11, in update\n",
      "    breakpoint()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 1610, in set_trace\n",
      "    pdb.set_trace(sys._getframe().f_back)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 326, in set_trace\n",
      "    self.reset()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 196, in reset\n",
      "    bdb.Bdb.reset(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 57, in reset\n",
      "    linecache.checkcache()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/compilerop.py\", line 157, in check_linecache_ipython\n",
      "    linecache._checkcache_ori(*args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 66, in checkcache\n",
      "    entry = cache[filename]\n",
      "KeyError: '<ipython-input-32-4047ee89f2b5>'\n",
      "\n",
      "\n",
      "Exception in thread Thread-328874:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-61-066f5069e308>\", line 11, in update\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 1610, in set_trace\n",
      "    pdb.set_trace(sys._getframe().f_back)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 326, in set_trace\n",
      "    self.reset()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 196, in reset\n",
      "    bdb.Bdb.reset(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 57, in reset\n",
      "    linecache.checkcache()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/compilerop.py\", line 157, in check_linecache_ipython\n",
      "    linecache._checkcache_ori(*args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 66, in checkcache\n",
      "    entry = cache[filename]\n",
      "KeyError: '<ipython-input-40-74332a430654>'\n",
      "\n",
      "Exception in thread Thread-328872:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 74, in checkcache\n",
      "    stat = os.stat(fullname)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '<ipython-input-53-a33471e3ed56>'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-61-066f5069e308>\", line 11, in update\n",
      "    breakpoint()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 1610, in set_trace\n",
      "    pdb.set_trace(sys._getframe().f_back)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 326, in set_trace\n",
      "    self.reset()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 196, in reset\n",
      "    bdb.Bdb.reset(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 57, in reset\n",
      "    linecache.checkcache()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/compilerop.py\", line 157, in check_linecache_ipython\n",
      "    linecache._checkcache_ori(*args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 76, in checkcache\n",
      "    del cache[filename]\n",
      "KeyError: '<ipython-input-53-a33471e3ed56>'\n",
      "Exception in thread Thread-328877:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 74, in checkcache\n",
      "    stat = os.stat(fullname)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '<ipython-input-25-4047ee89f2b5>'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-61-066f5069e308>\", line 11, in update\n",
      "    breakpoint()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 1610, in set_trace\n",
      "    pdb.set_trace(sys._getframe().f_back)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 326, in set_trace\n",
      "    self.reset()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 196, in reset\n",
      "    bdb.Bdb.reset(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 57, in reset\n",
      "    linecache.checkcache()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/compilerop.py\", line 157, in check_linecache_ipython\n",
      "    linecache._checkcache_ori(*args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 76, in checkcache\n",
      "    del cache[filename]\n",
      "KeyError: '<ipython-input-25-4047ee89f2b5>'\n",
      "Exception in thread Thread-328878:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-61-066f5069e308>\", line 11, in update\n",
      "    breakpoint()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 1610, in set_trace\n",
      "    pdb.set_trace(sys._getframe().f_back)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 326, in set_trace\n",
      "    self.reset()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 196, in reset\n",
      "    bdb.Bdb.reset(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 57, in reset\n",
      "    linecache.checkcache()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/compilerop.py\", line 157, in check_linecache_ipython\n",
      "    linecache._checkcache_ori(*args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 66, in checkcache\n",
      "    entry = cache[filename]\n",
      "KeyError: '<ipython-input-54-4047ee89f2b5>'\n",
      "Exception in thread Thread-328873:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 74, in checkcache\n",
      "    stat = os.stat(fullname)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '<ipython-input-15-de326a161aab>'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-61-066f5069e308>\", line 11, in update\n",
      "    breakpoint()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 1610, in set_trace\n",
      "    pdb.set_trace(sys._getframe().f_back)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 326, in set_trace\n",
      "    self.reset()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py\", line 196, in reset\n",
      "    bdb.Bdb.reset(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py\", line 57, in reset\n",
      "    linecache.checkcache()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/compilerop.py\", line 157, in check_linecache_ipython\n",
      "    linecache._checkcache_ori(*args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py\", line 76, in checkcache\n",
      "    del cache[filename]\n",
      "KeyError: '<ipython-input-15-de326a161aab>'\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(Pdb) ll\n",
      "  9  \t    def update(self):\n",
      " 10  \t        current_value = self.value\n",
      " 11  \t        breakpoint()\n",
      " 12  ->\t        self.value = current_value + 1\n",
      "(Pdb) p self.value\n",
      "0\n",
      "(Pdb) n\n",
      "--Return--\n",
      "> <ipython-input-61-066f5069e308>(12)update()->None\n",
      "-> self.value = current_value + 1\n",
      "(Pdb) p self.value\n",
      "1\n",
      "(Pdb) r\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py(874)run()\n",
      "-> del self._target, self._args, self._kwargs\n",
      "(Pdb) n\n",
      "--Return--\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py(874)run()->None\n",
      "-> del self._target, self._args, self._kwargs\n",
      "(Pdb) n\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py(967)_bootstrap_inner()\n",
      "-> pass\n",
      "(Pdb) n\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py(969)_bootstrap_inner()\n",
      "-> with _active_limbo_lock:\n",
      "(Pdb) n\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py(970)_bootstrap_inner()\n",
      "-> try:\n",
      "(Pdb) n\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py(973)_bootstrap_inner()\n",
      "-> del _active[get_ident()]\n",
      "(Pdb) n\n",
      "--Return--\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py(973)_bootstrap_inner()->None\n",
      "-> del _active[get_ident()]\n",
      "(Pdb) n\n",
      "--Return--\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py(890)_bootstrap()->None\n",
      "-> self._bootstrap_inner()\n",
      "(Pdb) n\n",
      "--Call--\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zmq/sugar/socket.py(65)__del__()\n",
      "-> def __del__(self):\n",
      "(Pdb) n\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zmq/sugar/socket.py(66)__del__()\n",
      "-> if not self._shadow:\n",
      "(Pdb) n\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zmq/sugar/socket.py(67)__del__()\n",
      "-> self.close()\n",
      "(Pdb) n\n",
      "--Return--\n",
      "> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zmq/sugar/socket.py(67)__del__()->None\n",
      "-> self.close()\n",
      "(Pdb) n\n"
     ]
    }
   ],
   "source": [
    "sample_counter = nCounter(10)\n",
    "sample_counter.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
